# Server defaults.
#port: 4000

# Project defaults.
markdown: kramdown #redcarpet
pygments: false
lsi: false
safe: false

#permalink: /news/:year/:month/:day/:title.html

exclude: ["node_modules", "scripts", "sass", "app.yaml", "README.md",
          "CONTRIBUTING.md", "Gruntfile.js", "package.json", "config.rb",
          "build.py"]

kramdown:
  #toc_levels: "2,3"
  toc_levels: 2..3
  #auto_ids: true

# Site globals used throughout docs.
load_platform: true
project_title: Polymer
latest_version: 0.1.2
add_permalinks: true # adds permalinks to heading tags.
load_disqus: true
